### ISSUE TITLE
Cannot find module 'newrelic-lambda-wrapper' after upgrade to 3.2.0

### ISSUE THREAD

**Issue by wbruno** [newrelic/serverless-newrelic-lambda-layers#245]
Hi, after upgrade this module to version 3.2.0. 100% of my lambda invocations started to fail on aws cloudwatch, with the following error.

```
2022-05-07T00:00:00.200Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'newrelic-lambda-wrapper'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'newrelic-lambda-wrapper'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

the hotfix was downgrade to 3.1.1

**Comment by mrickard** [comment]
@wbruno Do you import `newrelic-lambda-wrapper` directly in your function code?

**Comment by makarov-roman** [comment]
seems like it's happens when I deploy with `sls deploy function`, but deploying whole stack works fine

**Comment by mrickard** [comment]
@makarov-roman I see that you're using sls2. What happens if you update to sls3?

**Comment by makarov-roman** [comment]
@mrickard sorry, can't do that, since it requires more time than I can allocate on it atm.

**Comment by mrickard** [comment]
@makarov-roman and @wbruno If you check your serverless.yml plugins section, do you list this plugin last?

**Comment by wbruno** [comment]
I didn't, my last is `serverless-offline`. Do I need to list, after lambda-insights?

```
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-newrelic-lambda-layers
  - serverless-plugin-lambda-insights
  - serverless-prune-plugin
  - serverless-offline #needs to be last in the list
  ```

**Comment by mrickard** [comment]
@wbruno We recommend putting serverless-newrelic-lambda-layers last. If your serverless-offline plugin needs to be last, try putting serverless-newrelic-lambda-layers right before it.
